// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1-oneof-example.proto

public final class 1OneofExample {
  private 1OneofExample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessage2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMessage2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string my_string = 2;</code>
     * @return Whether the myString field is set.
     */
    boolean hasMyString();
    /**
     * <code>string my_string = 2;</code>
     * @return The myString.
     */
    java.lang.String getMyString();
    /**
     * <code>string my_string = 2;</code>
     * @return The bytes for myString.
     */
    com.google.protobuf.ByteString
        getMyStringBytes();

    /**
     * <code>bool my_bool = 3;</code>
     * @return Whether the myBool field is set.
     */
    boolean hasMyBool();
    /**
     * <code>bool my_bool = 3;</code>
     * @return The myBool.
     */
    boolean getMyBool();

    public 1OneofExample.MyMessage2.ExampleOneofCase getExampleOneofCase();
  }
  /**
   * Protobuf type {@code MyMessage2}
   */
  public static final class MyMessage2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MyMessage2)
      MyMessage2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage2.newBuilder() to construct.
    private MyMessage2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage2() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage2();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              exampleOneofCase_ = 2;
              exampleOneof_ = s;
              break;
            }
            case 24: {
              exampleOneofCase_ = 3;
              exampleOneof_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return 1OneofExample.internal_static_MyMessage2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return 1OneofExample.internal_static_MyMessage2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              1OneofExample.MyMessage2.class, 1OneofExample.MyMessage2.Builder.class);
    }

    private int exampleOneofCase_ = 0;
    private java.lang.Object exampleOneof_;
    public enum ExampleOneofCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      MY_STRING(2),
      MY_BOOL(3),
      EXAMPLEONEOF_NOT_SET(0);
      private final int value;
      private ExampleOneofCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ExampleOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static ExampleOneofCase forNumber(int value) {
        switch (value) {
          case 2: return MY_STRING;
          case 3: return MY_BOOL;
          case 0: return EXAMPLEONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ExampleOneofCase
    getExampleOneofCase() {
      return ExampleOneofCase.forNumber(
          exampleOneofCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int MY_STRING_FIELD_NUMBER = 2;
    /**
     * <code>string my_string = 2;</code>
     * @return Whether the myString field is set.
     */
    public boolean hasMyString() {
      return exampleOneofCase_ == 2;
    }
    /**
     * <code>string my_string = 2;</code>
     * @return The myString.
     */
    public java.lang.String getMyString() {
      java.lang.Object ref = "";
      if (exampleOneofCase_ == 2) {
        ref = exampleOneof_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (exampleOneofCase_ == 2) {
          exampleOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string my_string = 2;</code>
     * @return The bytes for myString.
     */
    public com.google.protobuf.ByteString
        getMyStringBytes() {
      java.lang.Object ref = "";
      if (exampleOneofCase_ == 2) {
        ref = exampleOneof_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (exampleOneofCase_ == 2) {
          exampleOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MY_BOOL_FIELD_NUMBER = 3;
    /**
     * <code>bool my_bool = 3;</code>
     * @return Whether the myBool field is set.
     */
    @java.lang.Override
    public boolean hasMyBool() {
      return exampleOneofCase_ == 3;
    }
    /**
     * <code>bool my_bool = 3;</code>
     * @return The myBool.
     */
    @java.lang.Override
    public boolean getMyBool() {
      if (exampleOneofCase_ == 3) {
        return (java.lang.Boolean) exampleOneof_;
      }
      return false;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (exampleOneofCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, exampleOneof_);
      }
      if (exampleOneofCase_ == 3) {
        output.writeBool(
            3, (boolean)((java.lang.Boolean) exampleOneof_));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (exampleOneofCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, exampleOneof_);
      }
      if (exampleOneofCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              3, (boolean)((java.lang.Boolean) exampleOneof_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof 1OneofExample.MyMessage2)) {
        return super.equals(obj);
      }
      1OneofExample.MyMessage2 other = (1OneofExample.MyMessage2) obj;

      if (getId()
          != other.getId()) return false;
      if (!getExampleOneofCase().equals(other.getExampleOneofCase())) return false;
      switch (exampleOneofCase_) {
        case 2:
          if (!getMyString()
              .equals(other.getMyString())) return false;
          break;
        case 3:
          if (getMyBool()
              != other.getMyBool()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      switch (exampleOneofCase_) {
        case 2:
          hash = (37 * hash) + MY_STRING_FIELD_NUMBER;
          hash = (53 * hash) + getMyString().hashCode();
          break;
        case 3:
          hash = (37 * hash) + MY_BOOL_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getMyBool());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static 1OneofExample.MyMessage2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1OneofExample.MyMessage2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1OneofExample.MyMessage2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1OneofExample.MyMessage2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1OneofExample.MyMessage2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1OneofExample.MyMessage2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1OneofExample.MyMessage2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 1OneofExample.MyMessage2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static 1OneofExample.MyMessage2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static 1OneofExample.MyMessage2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static 1OneofExample.MyMessage2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 1OneofExample.MyMessage2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(1OneofExample.MyMessage2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyMessage2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyMessage2)
        1OneofExample.MyMessage2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return 1OneofExample.internal_static_MyMessage2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return 1OneofExample.internal_static_MyMessage2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                1OneofExample.MyMessage2.class, 1OneofExample.MyMessage2.Builder.class);
      }

      // Construct using 1OneofExample.MyMessage2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        exampleOneofCase_ = 0;
        exampleOneof_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return 1OneofExample.internal_static_MyMessage2_descriptor;
      }

      @java.lang.Override
      public 1OneofExample.MyMessage2 getDefaultInstanceForType() {
        return 1OneofExample.MyMessage2.getDefaultInstance();
      }

      @java.lang.Override
      public 1OneofExample.MyMessage2 build() {
        1OneofExample.MyMessage2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public 1OneofExample.MyMessage2 buildPartial() {
        1OneofExample.MyMessage2 result = new 1OneofExample.MyMessage2(this);
        result.id_ = id_;
        if (exampleOneofCase_ == 2) {
          result.exampleOneof_ = exampleOneof_;
        }
        if (exampleOneofCase_ == 3) {
          result.exampleOneof_ = exampleOneof_;
        }
        result.exampleOneofCase_ = exampleOneofCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof 1OneofExample.MyMessage2) {
          return mergeFrom((1OneofExample.MyMessage2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(1OneofExample.MyMessage2 other) {
        if (other == 1OneofExample.MyMessage2.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        switch (other.getExampleOneofCase()) {
          case MY_STRING: {
            exampleOneofCase_ = 2;
            exampleOneof_ = other.exampleOneof_;
            onChanged();
            break;
          }
          case MY_BOOL: {
            setMyBool(other.getMyBool());
            break;
          }
          case EXAMPLEONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        1OneofExample.MyMessage2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (1OneofExample.MyMessage2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int exampleOneofCase_ = 0;
      private java.lang.Object exampleOneof_;
      public ExampleOneofCase
          getExampleOneofCase() {
        return ExampleOneofCase.forNumber(
            exampleOneofCase_);
      }

      public Builder clearExampleOneof() {
        exampleOneofCase_ = 0;
        exampleOneof_ = null;
        onChanged();
        return this;
      }


      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>string my_string = 2;</code>
       * @return Whether the myString field is set.
       */
      @java.lang.Override
      public boolean hasMyString() {
        return exampleOneofCase_ == 2;
      }
      /**
       * <code>string my_string = 2;</code>
       * @return The myString.
       */
      @java.lang.Override
      public java.lang.String getMyString() {
        java.lang.Object ref = "";
        if (exampleOneofCase_ == 2) {
          ref = exampleOneof_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (exampleOneofCase_ == 2) {
            exampleOneof_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string my_string = 2;</code>
       * @return The bytes for myString.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMyStringBytes() {
        java.lang.Object ref = "";
        if (exampleOneofCase_ == 2) {
          ref = exampleOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (exampleOneofCase_ == 2) {
            exampleOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string my_string = 2;</code>
       * @param value The myString to set.
       * @return This builder for chaining.
       */
      public Builder setMyString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  exampleOneofCase_ = 2;
        exampleOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string my_string = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMyString() {
        if (exampleOneofCase_ == 2) {
          exampleOneofCase_ = 0;
          exampleOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string my_string = 2;</code>
       * @param value The bytes for myString to set.
       * @return This builder for chaining.
       */
      public Builder setMyStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        exampleOneofCase_ = 2;
        exampleOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bool my_bool = 3;</code>
       * @return Whether the myBool field is set.
       */
      public boolean hasMyBool() {
        return exampleOneofCase_ == 3;
      }
      /**
       * <code>bool my_bool = 3;</code>
       * @return The myBool.
       */
      public boolean getMyBool() {
        if (exampleOneofCase_ == 3) {
          return (java.lang.Boolean) exampleOneof_;
        }
        return false;
      }
      /**
       * <code>bool my_bool = 3;</code>
       * @param value The myBool to set.
       * @return This builder for chaining.
       */
      public Builder setMyBool(boolean value) {
        exampleOneofCase_ = 3;
        exampleOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool my_bool = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMyBool() {
        if (exampleOneofCase_ == 3) {
          exampleOneofCase_ = 0;
          exampleOneof_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyMessage2)
    }

    // @@protoc_insertion_point(class_scope:MyMessage2)
    private static final 1OneofExample.MyMessage2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new 1OneofExample.MyMessage2();
    }

    public static 1OneofExample.MyMessage2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage2>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage2>() {
      @java.lang.Override
      public MyMessage2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public 1OneofExample.MyMessage2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMessage2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyMessage2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0251-oneof-example.proto\"Q\n\nMyMessage2\022\n\n" +
      "\002id\030\001 \001(\005\022\023\n\tmy_string\030\002 \001(\tH\000\022\021\n\007my_boo" +
      "l\030\003 \001(\010H\000B\017\n\rexample_oneofb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MyMessage2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyMessage2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyMessage2_descriptor,
        new java.lang.String[] { "Id", "MyString", "MyBool", "ExampleOneof", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
