// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/4-duration-example.proto

public final class 4DurationExample {
  private 4DurationExample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessage5OrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMessage5)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp msg_date = 1;</code>
     * @return Whether the msgDate field is set.
     */
    boolean hasMsgDate();
    /**
     * <code>.google.protobuf.Timestamp msg_date = 1;</code>
     * @return The msgDate.
     */
    com.google.protobuf.Timestamp getMsgDate();
    /**
     * <code>.google.protobuf.Timestamp msg_date = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getMsgDateOrBuilder();

    /**
     * <code>.google.protobuf.Duration validaty = 2;</code>
     * @return Whether the validaty field is set.
     */
    boolean hasValidaty();
    /**
     * <code>.google.protobuf.Duration validaty = 2;</code>
     * @return The validaty.
     */
    com.google.protobuf.Duration getValidaty();
    /**
     * <code>.google.protobuf.Duration validaty = 2;</code>
     */
    com.google.protobuf.DurationOrBuilder getValidatyOrBuilder();
  }
  /**
   * Protobuf type {@code MyMessage5}
   */
  public static final class MyMessage5 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MyMessage5)
      MyMessage5OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage5.newBuilder() to construct.
    private MyMessage5(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage5() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage5();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage5(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (msgDate_ != null) {
                subBuilder = msgDate_.toBuilder();
              }
              msgDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msgDate_);
                msgDate_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Duration.Builder subBuilder = null;
              if (validaty_ != null) {
                subBuilder = validaty_.toBuilder();
              }
              validaty_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(validaty_);
                validaty_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return 4DurationExample.internal_static_MyMessage5_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return 4DurationExample.internal_static_MyMessage5_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              4DurationExample.MyMessage5.class, 4DurationExample.MyMessage5.Builder.class);
    }

    public static final int MSG_DATE_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp msgDate_;
    /**
     * <code>.google.protobuf.Timestamp msg_date = 1;</code>
     * @return Whether the msgDate field is set.
     */
    @java.lang.Override
    public boolean hasMsgDate() {
      return msgDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp msg_date = 1;</code>
     * @return The msgDate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getMsgDate() {
      return msgDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : msgDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp msg_date = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getMsgDateOrBuilder() {
      return getMsgDate();
    }

    public static final int VALIDATY_FIELD_NUMBER = 2;
    private com.google.protobuf.Duration validaty_;
    /**
     * <code>.google.protobuf.Duration validaty = 2;</code>
     * @return Whether the validaty field is set.
     */
    @java.lang.Override
    public boolean hasValidaty() {
      return validaty_ != null;
    }
    /**
     * <code>.google.protobuf.Duration validaty = 2;</code>
     * @return The validaty.
     */
    @java.lang.Override
    public com.google.protobuf.Duration getValidaty() {
      return validaty_ == null ? com.google.protobuf.Duration.getDefaultInstance() : validaty_;
    }
    /**
     * <code>.google.protobuf.Duration validaty = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DurationOrBuilder getValidatyOrBuilder() {
      return getValidaty();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgDate_ != null) {
        output.writeMessage(1, getMsgDate());
      }
      if (validaty_ != null) {
        output.writeMessage(2, getValidaty());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgDate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMsgDate());
      }
      if (validaty_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getValidaty());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof 4DurationExample.MyMessage5)) {
        return super.equals(obj);
      }
      4DurationExample.MyMessage5 other = (4DurationExample.MyMessage5) obj;

      if (hasMsgDate() != other.hasMsgDate()) return false;
      if (hasMsgDate()) {
        if (!getMsgDate()
            .equals(other.getMsgDate())) return false;
      }
      if (hasValidaty() != other.hasValidaty()) return false;
      if (hasValidaty()) {
        if (!getValidaty()
            .equals(other.getValidaty())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgDate()) {
        hash = (37 * hash) + MSG_DATE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgDate().hashCode();
      }
      if (hasValidaty()) {
        hash = (37 * hash) + VALIDATY_FIELD_NUMBER;
        hash = (53 * hash) + getValidaty().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static 4DurationExample.MyMessage5 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 4DurationExample.MyMessage5 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 4DurationExample.MyMessage5 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 4DurationExample.MyMessage5 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 4DurationExample.MyMessage5 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 4DurationExample.MyMessage5 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 4DurationExample.MyMessage5 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 4DurationExample.MyMessage5 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static 4DurationExample.MyMessage5 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static 4DurationExample.MyMessage5 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static 4DurationExample.MyMessage5 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 4DurationExample.MyMessage5 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(4DurationExample.MyMessage5 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyMessage5}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyMessage5)
        4DurationExample.MyMessage5OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return 4DurationExample.internal_static_MyMessage5_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return 4DurationExample.internal_static_MyMessage5_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                4DurationExample.MyMessage5.class, 4DurationExample.MyMessage5.Builder.class);
      }

      // Construct using 4DurationExample.MyMessage5.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (msgDateBuilder_ == null) {
          msgDate_ = null;
        } else {
          msgDate_ = null;
          msgDateBuilder_ = null;
        }
        if (validatyBuilder_ == null) {
          validaty_ = null;
        } else {
          validaty_ = null;
          validatyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return 4DurationExample.internal_static_MyMessage5_descriptor;
      }

      @java.lang.Override
      public 4DurationExample.MyMessage5 getDefaultInstanceForType() {
        return 4DurationExample.MyMessage5.getDefaultInstance();
      }

      @java.lang.Override
      public 4DurationExample.MyMessage5 build() {
        4DurationExample.MyMessage5 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public 4DurationExample.MyMessage5 buildPartial() {
        4DurationExample.MyMessage5 result = new 4DurationExample.MyMessage5(this);
        if (msgDateBuilder_ == null) {
          result.msgDate_ = msgDate_;
        } else {
          result.msgDate_ = msgDateBuilder_.build();
        }
        if (validatyBuilder_ == null) {
          result.validaty_ = validaty_;
        } else {
          result.validaty_ = validatyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof 4DurationExample.MyMessage5) {
          return mergeFrom((4DurationExample.MyMessage5)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(4DurationExample.MyMessage5 other) {
        if (other == 4DurationExample.MyMessage5.getDefaultInstance()) return this;
        if (other.hasMsgDate()) {
          mergeMsgDate(other.getMsgDate());
        }
        if (other.hasValidaty()) {
          mergeValidaty(other.getValidaty());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        4DurationExample.MyMessage5 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (4DurationExample.MyMessage5) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Timestamp msgDate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> msgDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       * @return Whether the msgDate field is set.
       */
      public boolean hasMsgDate() {
        return msgDateBuilder_ != null || msgDate_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       * @return The msgDate.
       */
      public com.google.protobuf.Timestamp getMsgDate() {
        if (msgDateBuilder_ == null) {
          return msgDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : msgDate_;
        } else {
          return msgDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       */
      public Builder setMsgDate(com.google.protobuf.Timestamp value) {
        if (msgDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgDate_ = value;
          onChanged();
        } else {
          msgDateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       */
      public Builder setMsgDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (msgDateBuilder_ == null) {
          msgDate_ = builderForValue.build();
          onChanged();
        } else {
          msgDateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       */
      public Builder mergeMsgDate(com.google.protobuf.Timestamp value) {
        if (msgDateBuilder_ == null) {
          if (msgDate_ != null) {
            msgDate_ =
              com.google.protobuf.Timestamp.newBuilder(msgDate_).mergeFrom(value).buildPartial();
          } else {
            msgDate_ = value;
          }
          onChanged();
        } else {
          msgDateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       */
      public Builder clearMsgDate() {
        if (msgDateBuilder_ == null) {
          msgDate_ = null;
          onChanged();
        } else {
          msgDate_ = null;
          msgDateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getMsgDateBuilder() {
        
        onChanged();
        return getMsgDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getMsgDateOrBuilder() {
        if (msgDateBuilder_ != null) {
          return msgDateBuilder_.getMessageOrBuilder();
        } else {
          return msgDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : msgDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp msg_date = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getMsgDateFieldBuilder() {
        if (msgDateBuilder_ == null) {
          msgDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getMsgDate(),
                  getParentForChildren(),
                  isClean());
          msgDate_ = null;
        }
        return msgDateBuilder_;
      }

      private com.google.protobuf.Duration validaty_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> validatyBuilder_;
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       * @return Whether the validaty field is set.
       */
      public boolean hasValidaty() {
        return validatyBuilder_ != null || validaty_ != null;
      }
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       * @return The validaty.
       */
      public com.google.protobuf.Duration getValidaty() {
        if (validatyBuilder_ == null) {
          return validaty_ == null ? com.google.protobuf.Duration.getDefaultInstance() : validaty_;
        } else {
          return validatyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       */
      public Builder setValidaty(com.google.protobuf.Duration value) {
        if (validatyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          validaty_ = value;
          onChanged();
        } else {
          validatyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       */
      public Builder setValidaty(
          com.google.protobuf.Duration.Builder builderForValue) {
        if (validatyBuilder_ == null) {
          validaty_ = builderForValue.build();
          onChanged();
        } else {
          validatyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       */
      public Builder mergeValidaty(com.google.protobuf.Duration value) {
        if (validatyBuilder_ == null) {
          if (validaty_ != null) {
            validaty_ =
              com.google.protobuf.Duration.newBuilder(validaty_).mergeFrom(value).buildPartial();
          } else {
            validaty_ = value;
          }
          onChanged();
        } else {
          validatyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       */
      public Builder clearValidaty() {
        if (validatyBuilder_ == null) {
          validaty_ = null;
          onChanged();
        } else {
          validaty_ = null;
          validatyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       */
      public com.google.protobuf.Duration.Builder getValidatyBuilder() {
        
        onChanged();
        return getValidatyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       */
      public com.google.protobuf.DurationOrBuilder getValidatyOrBuilder() {
        if (validatyBuilder_ != null) {
          return validatyBuilder_.getMessageOrBuilder();
        } else {
          return validaty_ == null ?
              com.google.protobuf.Duration.getDefaultInstance() : validaty_;
        }
      }
      /**
       * <code>.google.protobuf.Duration validaty = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
          getValidatyFieldBuilder() {
        if (validatyBuilder_ == null) {
          validatyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                  getValidaty(),
                  getParentForChildren(),
                  isClean());
          validaty_ = null;
        }
        return validatyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyMessage5)
    }

    // @@protoc_insertion_point(class_scope:MyMessage5)
    private static final 4DurationExample.MyMessage5 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new 4DurationExample.MyMessage5();
    }

    public static 4DurationExample.MyMessage5 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage5>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage5>() {
      @java.lang.Override
      public MyMessage5 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage5(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage5> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage5> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public 4DurationExample.MyMessage5 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMessage5_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyMessage5_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036proto/4-duration-example.proto\032\037google" +
      "/protobuf/timestamp.proto\032\036google/protob" +
      "uf/duration.proto\"g\n\nMyMessage5\022,\n\010msg_d" +
      "ate\030\001 \001(\0132\032.google.protobuf.Timestamp\022+\n" +
      "\010validaty\030\002 \001(\0132\031.google.protobuf.Durati" +
      "onb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_MyMessage5_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyMessage5_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyMessage5_descriptor,
        new java.lang.String[] { "MsgDate", "Validaty", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
