// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 5-options-example.proto

package com.google.protobuf;

public final class DurationProto {
  private DurationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Duration2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Duration2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0275-options-example.proto\022\017google.protob" +
      "uf\"+\n\tDuration2\022\017\n\007seconds\030\001 \001(\003\022\r\n\005nano" +
      "s\030\002 \001(\005B|\n\023com.google.protobufB\rDuration" +
      "ProtoP\001Z*github.com/golang/protobuf/ptyp" +
      "es/duration\370\001\001\242\002\003GPB\252\002\036Google.Protobuf.W" +
      "ellKnownTypesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_protobuf_Duration2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Duration2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Duration2_descriptor,
        new java.lang.String[] { "Seconds", "Nanos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
